import "./globals.css";
import { Inter } from "next/font/google";

//components
import { Navbar } from "./components/NavBar/Index";
import { HeaderColor } from "./components/HeaderColor/Index";
import { TopHeader } from "./components/TopHeader/Index";
const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <script
          src="https://accounts.google.com/gsi/client"
          async
          defer
        ></script>
      </Head>
      <body className={inter.className}>
        <>
          <HeaderColor />
          <Navbar />
          <div className="_MainBodySection">
            <TopHeader />
            {children}
          </div>
        </>
      </body>
    </html>
  );
}
